[package]
name = "gitsha"
version = "0.1.0"
authors = ["Odin Dutton <odindutton@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
libflate = "0.1"
sha1 = "0.6"
crossbeam = "0.7"
num_cpus = "1.10"
